config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  post "log_out" => "sessions#destroy", as: "log_out"
  get "log_in" => "sessions#new", as: "log_in"
  get "sign_up" => "users#new", as: "sign_up"

  resources :sessions do
  end

  resources :users do
  end

  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

      user ||= User.new # guest user (not logged in)
      if user.has_role? :admin
        can :manage, :all
      else
        can :read, :all
      end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  #attr_accessible :email, :password, :password_confirmation, :remember_me, :roles

  #roles_attribute :roles_mask

  #roles :admin, :editor, :guest

  attr_accessor :password
  #validates :user_name, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :email, :presence => true, :uniqueness => true, :format => {:with  => Devise.email_regexp, :allow_blank => true, :if => :email_changed?}
  validates :password, :confirmation => true, :length => { :minimum => 6, :maximum => 15 } #password_confirmation attr

  before_save :encrypt_password
  after_save :clear_password

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.encrypted_password == BCrypt::Engine.hash_secret(password, user.salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def clear_password
      self.password = nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:profile]

  def index
    @users = User.all
  end

  def new
   @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_url, notice: "您已经成功注册!"
    else
      flash[:notice] = "您的信息填写有误，请重新填写！"
      render 'new'
    end

  end

  def show
    @user = User.find(params[:id])
  end

  def profile
    @profile = @user.profile
  end

  private
    def set_member
      @user = User.find params[:id]
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  ng-app>
<head>
  <title>Weiqi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <%= render "shared/navbar"%>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.haml
.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: "#"} Project name
    .navbar-collapse.collapse
      - if current_user
        .navbar-form.navbar-right
          %a.navbar-brand{href: "#"} #{current_user.email}
          = button_to "Log out", log_out_path, class: 'button btn btn-success'
      - elsif request.path != "/log_in"
        = form_tag user_session_path, role: 'form', class: ' navbar-form navbar-right' do
          .form-group
            = text_field_tag :email, params[:email], placeholder: '输入您的邮箱', class: 'form-control'
          .form-group
            = password_field_tag :password, params[:password], placeholder: '输入您的密码', class: 'form-control', required: ''
          = submit_tag "登录", class: 'btn btn-success'
    / /.navbar-collapse
/ Main jumbotron for a primary marketing message or call to action

app/views/users/_user.html.haml
%p
  %strong
    Email:
  = u.email

app/views/users/index.html.haml
%h1 User#index
%p Find me in app/views/user/index.html.haml
= @users.each do |u|
  = render partial: 'user', locals: {u: u}

app/views/users/new.html.haml
.container
  .form-signup
    = form_for @user do |f|
      %h2
        .form-signup-heading
          请您填写您的相关信息
      = f.text_field :email, placeholder: '用于注册的邮箱', class: 'form-control', required: '', autofocus: ''
      = f.password_field :password, placeholder: '输入您想要设置的密码', class: 'form-control', required: ''
      = f.password_field :password_confirmation, placeholder: '确认您的密码', class: 'form-control', required: ''
      = f.submit '注册', class: 'btn btn-lg btn-primary btn-block'

app/views/users/show.html.haml
%h1 User#show
%p Find me in app/views/user/show.html.haml
%p
  %strong
    UserName:
  = @user.user_name

app/views/welcome/index.html.haml
.jumbotron
  .container
    Hello {{'World'}}!
    %h1 Hello, world!
    %p This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.
    %p
      %a.btn.btn-primary.btn-lg{role: "button"} Learn more »
.container
  / Example row of columns
  .row
    .col-md-4
      %h2 Heading
      %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
      %p
        %a.btn.btn-default{href: "#", role: "button"} View details »
    .col-md-4
      %h2 Heading
      %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
      %p
        %a.btn.btn-default{href: "#", role: "button"} View details »
    .col-md-4
      %h2 Heading
      %p Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
      %p
        %a.btn.btn-default{href: "#", role: "button"} View details »
  %hr/
  %footer
    %p © Company 2014